language: csharp
solution: Evos.sln
install:
  - nuget restore Evos.sln
script:
  - xbuild /p:Configuration=Release Evos.sln
  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe ./Sequence.Tests/bin/Debug/Sequence.Tests.dll
